#ifndef __CM_SOUND_INCLUDED__
#define __CM_SOUND_INCLUDED__


//#include "stm32f4xx_hal.h"


typedef enum {
    SOUND_CMD_STOP,
    SOUND_CMD_SET_SOUND_SET_EN,
    SOUND_CMD_SET_SOUND_SET_CZ,
    SOUND_CMD_PLAY_ACTIVATED,
    SOUND_CMD_PLAY_GUN,
    SOUND_CMD_PLAY_DONT_GIVE_UP,
    SOUND_CMD_PLAY_GAME_OVER,
    SOUND_CMD_PLAY_GO,
    SOUND_CMD_PLAY_KEEP_GOING,
    SOUND_CMD_PLAY_NUMBER_1,
    SOUND_CMD_PLAY_NUMBER_2,
    SOUND_CMD_PLAY_NUMBER_3,
    SOUND_CMD_PLAY_NUMBER_4,
    SOUND_CMD_PLAY_NUMBER_5,
    SOUND_CMD_PLAY_PLAY,
    SOUND_CMD_PLAY_WELL_DONE
} sound_cmd_t;

typedef enum {
    SOUND_SET_EN,
    SOUND_SET_CZ,
} sound_set_t;

#endif // ifndef __CM_SOUND_INCLUDED__
